console.log(window)
console.dir(document.body.childNodes)
document.body.style.background="green"
let heading= document.getElementById("header")
console.dir(heading.innerText)
let head=document.getElementsByClassName("heading")
console.log(head)
console.dir(head)
let para=document.querySelector("p")
console.log(para)
console.log(para.tagName)
let btn=document.querySelector("button")
console.log(btn.tagName)
console.log("btn")
let content1=document.querySelector("div").children
console.log(content1)
let content=document.querySelectorAll("div")
console.log(content)
console.log(content[1])
1